
##jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prod
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


  ####显示sql语句
  jpa:
    show-sql: true


##web路径与端口
server:
  port: 7777
  servlet:
    context-path: /pctcprod
